name: Jest Tests

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Run tests
        # Suppress normal error logs.
        run: yarn test --silent
    env:
      NODE_ENV: test
      AWS_DB: ${{ secrets.AWS_DB }}
      AWS_DB_ENDPOINT: ${{ secrets.AWS_DB_ENDPOINT }}
      AWS_DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
      AWS_DB_USER: ${{ secrets.AWS_DB_USER }}
      GC_API_KEY: ${{ secrets.GC_API_KEY }}
      NEXT_PUBLIC_STRIPE_TOKEN: ${{ secrets.NEXT_PUBLIC_STRIPE_TOKEN }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      MJ_PUBLIC: ${{ secrets.MJ_PUBLIC }}
      MJ_SECRET: ${{ secrets.MJ_SECRET }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
